### ISSUE TITLE
Sequences loss after clustering?

### ISSUE THREAD

**Issue by pwwang** [svalkiers/clusTCR#32]
```python
>>> import clustcr as ct
>>> cdr3 = ct.datasets.test_cdr3()
>>> cdr3.size
2851
>>> cdr3.unique().size
2851
>>> clustering = ct.Clustering()
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                 CDR3  cluster
0     CASSLGQGHYNEQFF        0
1     CASSPGQGHYNEQFF        0
2     CASSSGTGPNEKLFF        1
3     CASTSGTGPNEKLFF        1
4     CASSPGTAPNEKLFF        1
..                ...      ...
637    CASSLQGSNQPQHF      199
638     CASSDSGTDTQYF      200
639     CASSLSGTDTQYF      200
640  CSARAGGGEAKNIQYF      201
641  CSARASGGEAKNIQYF      201

[642 rows x 2 columns]
>>> sum(len(seqs) for seqs in output.cluster_contents())
642
```

Where are the rest 2851 - 641 = 2210 sequences?

```python
>>> clustering = ct.Clustering(method="mcl")
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                 CDR3  cluster
0     CASSLGQGHYNEQFF        0
1     CASSPGQGHYNEQFF        0
2     CASSSGTGPNEKLFF        1
3     CASTSGTGPNEKLFF        1
4     CASSPGTAPNEKLFF        1
..                ...      ...
637    CASSLQGSNQPQHF      199
638     CASSDSGTDTQYF      200
639     CASSLSGTDTQYF      200
640  CSARAGGGEAKNIQYF      201
641  CSARASGGEAKNIQYF      201

[642 rows x 2 columns]
```

```python
>>> clustering = ct.Clustering(method="two-step")
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                 CDR3  cluster
0     CASSLGQGHYNEQFF        0
1     CASSPGQGHYNEQFF        0
2     CASSSGTGPNEKLFF        1
3     CASTSGTGPNEKLFF        1
4     CASSPGTAPNEKLFF        1
..                ...      ...
637    CASSLQGSNQPQHF      199
638     CASSDSGTDTQYF      200
639     CASSLSGTDTQYF      200
640  CSARAGGGEAKNIQYF      201
641  CSARASGGEAKNIQYF      201

[642 rows x 2 columns]
```

Also wired that different methods resulted in the same size of `clusters_df`.

```python
>>> import importlib.metadata
>>> importlib.metadata.version("clustcr")
'0+untagged.115.gba1ad3c'
```

**Comment by pwwang** [comment]
With the latest version by `pip install git+https://github.com/svalkiers/clusTCR.git` @ b6181181fa9bb3dd9bf875ebf3c711ba6930c664 :

```python
>>> import clustcr as ct
>>> cdr3 = ct.datasets.test_cdr3()
>>> clustering = ct.Clustering()
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                 CDR3 cluster
0       CASTPQGAYEQYF       0
1       CASTPTGAYEQYF       0
2        CASSLGQIEQYF       1
3        CASSLGQKEQYF       1
4        CASSLGQGEQYF       1
..                ...     ...
789      CASSEGSQEVFF     237
790  CSARAGGGEAKNIQYF     238
791  CSARASGGEAKNIQYF     238
792     CASSDSGTDTQYF     239
793     CASSLSGTDTQYF     239

[794 rows x 2 columns]

>>> clustering = ct.Clustering(method="mcl")
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                 CDR3  cluster
0       CASTPQGAYEQYF        0
1       CASTPTGAYEQYF        0
2        CASSLGQIEQYF        1
3        CASSLGQKEQYF        1
4        CASSLGQGEQYF        1
..                ...      ...
789      CASSEGSQEVFF      237
790  CSARAGGGEAKNIQYF      238
791  CSARASGGEAKNIQYF      238
792     CASSDSGTDTQYF      239
793     CASSLSGTDTQYF      239

[794 rows x 2 columns]

>>> clustering.method
'MCL'
>>> clustering = ct.Clustering(method="faiss")
>>> clustering.method
'FAISS'
>>> output = clustering.fit(cdr3)
>>> output.clusters_df
                      CDR3  cluster
0     CASSYLPGQGDHYSNQPQHF        0
1      CASSFEAGQGFFSNQPQHF        0
2      CASSFEPGQGFYSNQPQHF        0
3     CASSYEPGQVSHYSNQPQHF        0
4            CASSFGVEDEQYF        0
...                    ...      ...
3387        CATSDVNGAYEQYF        0
3388        CSARGGSVFYEQYF        0
3389        CSARGGERFYEQYF        0
3390      CASSASTSDYSYEQYF        0
3391      CASSDLTGTAYNEQFF        0

[3392 rows x 2 columns]
```

`faiss` method even resulted in all seqs being clustered to `0`.

```python
>>> import importlib.metadata
>>> importlib.metadata.version("clustcr")
'0+untagged.267.gb618118'
```

**Comment by svalkiers** [comment]
> ```python
> >>> import clustcr as ct
> >>> cdr3 = ct.datasets.test_cdr3()
> >>> cdr3.size
> 2851
> >>> cdr3.unique().size
> 2851
> >>> clustering = ct.Clustering()
> >>> output = clustering.fit(cdr3)
> >>> output.clusters_df
>                  CDR3  cluster
> 0     CASSLGQGHYNEQFF        0
> 1     CASSPGQGHYNEQFF        0
> 2     CASSSGTGPNEKLFF        1
> 3     CASTSGTGPNEKLFF        1
> 4     CASSPGTAPNEKLFF        1
> ..                ...      ...
> 637    CASSLQGSNQPQHF      199
> 638     CASSDSGTDTQYF      200
> 639     CASSLSGTDTQYF      200
> 640  CSARAGGGEAKNIQYF      201
> 641  CSARASGGEAKNIQYF      201
> 
> [642 rows x 2 columns]
> >>> sum(len(seqs) for seqs in output.cluster_contents())
> 642
> ```
> 
> Where are the rest 2851 - 641 = 2210 sequences?
> 
> ```python
> >>> clustering = ct.Clustering(method="mcl")
> >>> output = clustering.fit(cdr3)
> >>> output.clusters_df
>                  CDR3  cluster
> 0     CASSLGQGHYNEQFF        0
> 1     CASSPGQGHYNEQFF        0
> 2     CASSSGTGPNEKLFF        1
> 3     CASTSGTGPNEKLFF        1
> 4     CASSPGTAPNEKLFF        1
> ..                ...      ...
> 637    CASSLQGSNQPQHF      199
> 638     CASSDSGTDTQYF      200
> 639     CASSLSGTDTQYF      200
> 640  CSARAGGGEAKNIQYF      201
> 641  CSARASGGEAKNIQYF      201
> 
> [642 rows x 2 columns]
> ```
> 
> ```python
> >>> clustering = ct.Clustering(method="two-step")
> >>> output = clustering.fit(cdr3)
> >>> output.clusters_df
>                  CDR3  cluster
> 0     CASSLGQGHYNEQFF        0
> 1     CASSPGQGHYNEQFF        0
> 2     CASSSGTGPNEKLFF        1
> 3     CASTSGTGPNEKLFF        1
> 4     CASSPGTAPNEKLFF        1
> ..                ...      ...
> 637    CASSLQGSNQPQHF      199
> 638     CASSDSGTDTQYF      200
> 639     CASSLSGTDTQYF      200
> 640  CSARAGGGEAKNIQYF      201
> 641  CSARASGGEAKNIQYF      201
> 
> [642 rows x 2 columns]
> ```
> 
> Also wired that different methods resulted in the same size of `clusters_df`.
> 
> ```python
> >>> import importlib.metadata
> >>> importlib.metadata.version("clustcr")
> '0+untagged.115.gba1ad3c'
> ```

To answer your first question, ClusTCR takes into account all sequences, but not every sequence does belong to a cluster. This is an inherent result of the clustering procedure. In its second pass, ClusTCR builds a network where edges are drawn between sequences only if they differ 1 hamming distance (amino acid edit distance) at most. Thus, sequences that have no such connection will not be part of the network and therefore considered outliers. As such, they are not reported in the clustering results.

**Comment by pwwang** [comment]
WOW! Super clear explanation! Appreciate it! 👍
