### ISSUE TITLE
Could you please create a release

### ISSUE THREAD

**Issue by fizwit** [svalkiers/clusTCR#41]
To promote reproducible science, could you please use git tags. Creating a tag also creates a release for your project. We require tagged releases when building scientific software.  Pulling from the master is not reproducible.

I would also recommend using the standard for semantic versioning. (Semver)[https://semver.org/]
Version number in the form: Magor.Minor.Patch.  Please do not
follow the git examples by putting a "v" as the leading character. Github will create a "release" when the tag is pushed.

Thank you for making your software available

**Comment by svalkiers** [comment]
Hi, thank you for pointing this out. Reproducibility is a key pillar of science. Therefore, any changes to the ClusTCR codebase will be tagged from this point onwards.

Cheers,
Sebastiaan
