### ISSUE TITLE
Clustering method for TCRdist

### ISSUE THREAD

**Issue by jiangdada1221** [svalkiers/clusTCR#45]
Hi, I'm wondering what's the clustering method for TCRdist since it only gives the pairwise similarity scores. I observed many options in the tcrdist module in this repository. Thus, which one did you use for evaluating TCRdist?

Best,
Yuepeng

**Comment by svalkiers** [comment]
Hi there! Indeed, there is no fixed value for TCRdist. For our benchmark comparisons, we evaluated the trade-off between clustering purity, consistency and retention and choose the TCRdist value that best reflected the clustering retention of the other methods included in the benchmarking (GLIPH2 & iSMART).

You can read more about the exact approach in the supplementary material of our [publication](https://academic.oup.com/bioinformatics/article/37/24/4865/6300511). Feel free to reach out if you have any more questions.
